---
id: Editor
name: Editor
full: WYSIWYG editor library
description: >
  The Horde_Editor package provides an API to generate the code necessary for
  embedding javascript RTE editors in a web page.
list: dev
type: library
