---
id: Editor
name: Editor
full: WYSIWYG editor library
description: >-
  A library to generate the code necessary for embedding javascript RTE editors
  in a web page.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Editor
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Browser: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Serialize: ^2
